spring.application.name=makemytrip
server.port=${PORT:8080}
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://PBatRJXPM8tIDH43:PBatRJXPM8tIDH43@connectify-cluster.uieqfq3.mongodb.net/makemytrip?retryWrites=true&w=majority&appName=connectify-cluster}
spring.data.mongodb.database=makemytrip
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
